### ISSUE TITLE
GoogleSlides2md

### ISSUE THREAD

**Issue by jagadishreddykovvuri** [googleworkspace/md2googleslides#76] opened 2020-04-22 13:22 UTC
I want to convert google slides to md files is there any package

**Comment by bwplotka** [comment] 2020-06-07 14:39
As far as I know, there is no package for this (: 

It would be nice to have, but I think impossible / hard to implement. at current moment.

**Comment by bwplotka** [comment] 2020-06-07 14:42
Also this is duplicate of https://github.com/gsuitedevs/md2googleslides/issues/10

**Closed** 2021-02-23 19:32 UTC
